server:
  port: 10015
  max-http-header-size: 8192
  tomcat:
    accesslog:
      enabled: true
      directory: access_log
      prefix: access_log
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" "%{X-Forwarded-For}i" "%{X-Real-IP}i" %D %S "%U" %v'
    basedir: ./
spring:
  application:
    name: movie-recommend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    username: xxxxxx # 用户名
    password: xxxxxx # 密码
    url: jdbc:mysql://x.x.x.x:post/movie?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
  redis:
    timeout: 300s # 超时时间
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8 #最大连接数
        max-active: 20 # 最大连接数,-1为不限制
        min-idle: 0 # 最小空闲数量
        max-wait: 1s # 最大阻塞等待时间，-1为不限制
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        globally_quoted_identifiers: true